apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
  namespace: default
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: http://127.0.0.1:8200
  - name: skipVerify # Optional. Default: false
    value : true
  - name: vaultToken # Required if vaultTokenMountPath not provided. Token value.
    value : hvs.8QDcyP5pwwk9yPFXv803JmxU
  - name: vaultKVUsePrefix # Optional. default: "true"
    value: false
  - name: enginePath # Optional. default: "secret"
    value: kv
  - name: vaultValueType # Optional. default: "map"
    value: map