apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: signalrhub
spec:
  type: bindings.azure.signalr
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: dapr
      key: signalr
  - name: hub  # Optional
    value: orders
auth:
  secretStore: vault
scopes:
- make-line-service
